### PR TITLE
Fix for #5 and #6 to restore functionality with and without selection

### PR DESCRIPTION
**Pull request by kevinold**
I have been able to secure a fix for using this extension with pages that I haven't been able to in months.

This also allows for selections from the page to be in the body.

### CODE REVIEW

**Comment by pepelsbey** [comment]
Thank you for PR! I’ll check it shortly, merge it and put extension back to store. But there’s a small code style detail: could you please install [EditorConfig](http://editorconfig.org/) plugin for your editor to align code with project’s code style? See [.editorconfig](https://github.com/pepelsbey/add-to-things/blob/master/.editorconfig) file. With such plugin your editor will use correct style. Single quotes are also preferable. I hope it’s not too much to ask :)

**Comment by pepelsbey** [comment]
It works great! Even faster than it used to. Can’t wait to merge and release it.

**Comment by kevinold** [comment]
@pepelsbey Thanks!  I've fixed, so it's ready to merge.

**Comment by pepelsbey** [comment]
Thank you!

**Pull request merged**
